services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    # ports:
    #   - "5433:5432"
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
  backend:
    build: ./Asset-Management-BE
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:8080"
    env_file:
      - .env.docker
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres-db

  frontend:
    build: ./Asset-Management-FE
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - API_BASE_URL=http://backend:8080/api
      - NEXTAUTH_URL=http://asset.tonkla.studio
      - NEXTAUTH_URL_INTERNAL=http://127.0.0.1:3000
      - NODE_OPTIONS=--dns-result-order=ipv4first
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local