--
-- PostgreSQL database dump
--

\restrict BJVyiqoiVxVur4lQ0TqYkIyMAQaTPc1eysIPINtwYO5ZIiWIsOVbzq0Fp8fGxyx

-- Dumped from database version 17.10 (21f7c76)
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: asset_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.asset_logs (
    id integer NOT NULL,
    asset_id integer,
    action text NOT NULL,
    note text NOT NULL,
    created_by integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: asset_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.asset_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assets (
    id integer NOT NULL,
    main_serial_number text NOT NULL,
    serial_number text NOT NULL,
    asset_name text NOT NULL,
    location text,
    status text NOT NULL,
    condition text NOT NULL,
    owner_name text,
    acquired_date timestamp with time zone,
    created_by integer,
    created_at timestamp with time zone,
    updated_by integer,
    updated_at timestamp with time zone,
    fiscal_year text,
    main_sequence_no text,
    item_sequence_no integer,
    item_sequence_name text,
    budget_type integer DEFAULT 0 NOT NULL
);


--
-- Name: assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repairs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repairs (
    id integer NOT NULL,
    asset_id integer NOT NULL,
    description text NOT NULL,
    status text NOT NULL,
    type text NOT NULL,
    reported_by integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: repairs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.repairs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repairs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    azure_id text NOT NULL,
    last_login_at timestamp with time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: asset_logs pk_asset_logs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_logs
    ADD CONSTRAINT pk_asset_logs PRIMARY KEY (id);


--
-- Name: assets pk_assets; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT pk_assets PRIMARY KEY (id);


--
-- Name: repairs pk_repairs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repairs
    ADD CONSTRAINT pk_repairs PRIMARY KEY (id);


--
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);


--
-- Name: ix_asset_logs_asset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_asset_logs_asset_id ON public.asset_logs USING btree (asset_id);


--
-- Name: ix_repairs_asset_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_repairs_asset_id ON public.repairs USING btree (asset_id);


--
-- Name: ix_users_username; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_users_username ON public.users USING btree (name);


--
-- Name: asset_logs fk_asset_logs_assets_asset_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_logs
    ADD CONSTRAINT fk_asset_logs_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE CASCADE;


--
-- Name: asset_logs fk_asset_logs_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.asset_logs
    ADD CONSTRAINT fk_asset_logs_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: assets fk_assets_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fk_assets_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: assets fk_assets_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT fk_assets_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: repairs fk_repairs_assets_asset_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repairs
    ADD CONSTRAINT fk_repairs_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE CASCADE;


--
-- Name: repairs fk_repairs_reported_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repairs
    ADD CONSTRAINT fk_repairs_reported_by FOREIGN KEY (reported_by) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict BJVyiqoiVxVur4lQ0TqYkIyMAQaTPc1eysIPINtwYO5ZIiWIsOVbzq0Fp8fGxyx

